#
#spring:
#  profiles:
#    active: local
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/jejudata
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        #show_sql: true
#        format_sql: true
#        use_sql_comments: true
#

server:
  servlet:
    session:
      tracking-modes: cookie


#  thymeleaf:
#    #prefix: classpath:src/main/resources/
#    check-template-location: true
#    suffix: .html
#    mode: HTML
#    cache: false
#    order: 0


logging.level:
  org.hibernate.SQL: debug
  #  org.hibernate.type: trace


spring :
  datasource :
    driver-class-name : com.mysql.cj.jdbc.Driver # MySQL 설정
    url : jdbc:mysql://localhost:3306/Test1
    username : root
    password : Jinchan0312!@
  jpa :
    show-sql : true # true 설정시 JPA 쿼리문 확인 가능
    hibernate :
      ddl-auto : update # DDL(create, alter, drop) 정의시 DB의 고유 기능을 사용할 수 있다.
    properties :
      hibernate :
        format_sql : true # JPA의 구현체인 Hibernate가 동작하면서 발생한 SQL의 가독성을 높여준다.

